export const ASYNC_START = 'SHARED_ASYNC_START';
export const ASYNC_END = 'SHARED_ASYNC_END';
export const LOGIN = 'SHARED_LOGIN';
export const LOGOUT = 'SHARED_LOGOUT';
export const REGISTER = 'SHARED_REGISTER';

//ADD SHARED_


export const SHARED_FETCH_HOME_DATA = 'SHARED_FETCH_HOME_DATA';
export const SHARED_POST_HOME_DATA = 'SHARED_POST_HOME_DATA';
export const SHARED_LOADING_HOME_DATA = 'SHARED_LOADING_HOME_DATA';
export const SHARED_ERROR_HOME_DATA = 'SHARED_ERROR_HOME_DATA';
export const SHARED_ERROR_HOME_DATA_DISPLAYED = 'SHARED_ERROR_HOME_DATA_DISPLAYED';
