export const SHARED_LOGIN_USER_SUCCESS = 'SHARED_LOGIN_USER_SUCCESS';
export const SHARED_AUTH_ERROR = 'SHARED_AUTH_ERROR';
export const SHARED_LOADING_AUTH_USER = 'SHARED_LOADING_AUTH_USER';
export const SHARED_AUTH_ERROR_DISPLAYED = 'SHARED_AUTH_ERROR_DISPLAYED';
export const SHARED_APP_LOADING = 'SHARED_APP_LOADING';
export const SHARED_LOGOUT = 'SHARED_LOGOUT';

export const SHARED_FETCH_HOME_DATA = 'SHARED_FETCH_HOME_DATA';
export const SHARED_POST_HOME_DATA = 'SHARED_POST_HOME_DATA';
export const SHARED_LOADING_HOME_DATA = 'SHARED_LOADING_HOME_DATA';
export const SHARED_ERROR_HOME_DATA = 'SHARED_ERROR_HOME_DATA';
export const SHARED_ERROR_HOME_DATA_DISPLAYED = 'SHARED_ERROR_HOME_DATA_DISPLAYED';
