export const SHARED_LOGIN_USER_SUCCESS = 'SHARED_LOGIN_USER_SUCCESS';
export const SHARED_AUTH_ERROR = 'SHARED_AUTH_ERROR';
export const SHARED_LOADING_AUTH_USER = 'SHARED_LOADING_AUTH_USER';
export const SHARED_AUTH_ERROR_DISPLAYED = 'SHARED_AUTH_ERROR_DISPLAYED';
export const SHARED_APP_LOADING = 'SHARED_APP_LOADING';
export const SHARED_LOGOUT = 'SHARED_LOGOUT';

export const SHARED_FETCH_ACCOUNTS_DATA = 'SHARED_FETCH_ACCOUNTS_DATA';
export const SHARED_LOADING_ACCOUNTS = 'SHARED_LOADING_ACCOUNTS';
export const SHARED_ERROR_ACCOUNTS = 'SHARED_ERROR_ACCOUNTS';
export const SHARED_ERROR_DISPLAYED_ACCOUNTS = 'SHARED_ERROR_DISPLAYED_ACCOUNTS';

export const SHARED_SELECT_ACCOUNT_FROM_TRANSFER = 'SHARED_SELECT_ACCOUNT_FROM_TRANSFER';
export const SHARED_UNSELECT_ACCOUNT_FROM_TRANSFER = 'SHARED_UNSELECT_ACCOUNT_FROM_TRANSFER';
export const SHARED_SELECT_ACCOUNT_TO_TRANSFER = 'SHARED_SELECT_ACCOUNT_TO_TRANSFER';
export const SHARED_UNSELECT_ACCOUNT_TO_TRANSFER = 'SHARED_UNSELECT_ACCOUNT_TO_TRANSFER';
export const SHARED_SET_AMOUNT_TO_TRANSFER = 'SHARED_SET_AMOUNT_TO_TRANSFER';
export const SHARED_POST_TRANSFER = 'SHARED_POST_TRANSFER';
export const SHARED_COMPLETED_DISPLAYED_TRANSFER = 'SHARED_COMPLETED_DISPLAYED_TRANSFER';
export const SHARED_LOADING_TRANSFER = 'SHARED_LOADING_TRANSFER';
export const SHARED_ERROR_TRANSFER = 'SHARED_ERROR_TRANSFER';
export const SHARED_ERROR_DISPLAYED_TRANSFER = 'SHARED_ERROR_DISPLAYED_TRANSFER';
